package com.company.core.mapper;

import com.company.core.dao.TblAlismsConfigDAO;
import com.company.core.dao.TblAlismsConfigDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblAlismsConfigDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int countByExample(TblAlismsConfigDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int deleteByExample(TblAlismsConfigDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String smsChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int insert(TblAlismsConfigDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int insertSelective(TblAlismsConfigDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    List<TblAlismsConfigDAO> selectByExample(TblAlismsConfigDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    TblAlismsConfigDAO selectByPrimaryKey(String smsChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblAlismsConfigDAO record, @Param("example") TblAlismsConfigDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblAlismsConfigDAO record, @Param("example") TblAlismsConfigDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblAlismsConfigDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ALISMS_CONFIG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblAlismsConfigDAO record);
}