package com.company.core.mapper;

import com.company.core.dao.TblSmsRouteDAO;
import com.company.core.dao.TblSmsRouteDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSmsRouteDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int countByExample(TblSmsRouteDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int deleteByExample(TblSmsRouteDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String smsCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int insert(TblSmsRouteDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int insertSelective(TblSmsRouteDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    List<TblSmsRouteDAO> selectByExample(TblSmsRouteDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    TblSmsRouteDAO selectByPrimaryKey(String smsCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblSmsRouteDAO record, @Param("example") TblSmsRouteDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblSmsRouteDAO record, @Param("example") TblSmsRouteDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblSmsRouteDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_ROUTE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblSmsRouteDAO record);
}