package com.company.core.mapper;

import com.company.core.dao.TblSmsRecordDAO;
import com.company.core.dao.TblSmsRecordDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSmsRecordDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int countByExample(TblSmsRecordDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(TblSmsRecordDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String smsOrderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int insert(TblSmsRecordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(TblSmsRecordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    List<TblSmsRecordDAO> selectByExample(TblSmsRecordDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    TblSmsRecordDAO selectByPrimaryKey(String smsOrderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblSmsRecordDAO record, @Param("example") TblSmsRecordDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblSmsRecordDAO record, @Param("example") TblSmsRecordDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblSmsRecordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblSmsRecordDAO record);
}