package com.company.core.mapper;

import com.company.core.dao.TblSmsVerifyCodeDAO;
import com.company.core.dao.TblSmsVerifyCodeDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSmsVerifyCodeDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int countByExample(TblSmsVerifyCodeDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int deleteByExample(TblSmsVerifyCodeDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String phoneNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int insert(TblSmsVerifyCodeDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int insertSelective(TblSmsVerifyCodeDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    List<TblSmsVerifyCodeDAO> selectByExample(TblSmsVerifyCodeDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    TblSmsVerifyCodeDAO selectByPrimaryKey(String phoneNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblSmsVerifyCodeDAO record, @Param("example") TblSmsVerifyCodeDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblSmsVerifyCodeDAO record, @Param("example") TblSmsVerifyCodeDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblSmsVerifyCodeDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_VERIFY_CODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblSmsVerifyCodeDAO record);
}