package com.company.core.dao;

public class TblAlismsConfigDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.SMS_CHANNEL_ID
     *
     * @mbggenerated
     */
    private String smsChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.SMS_CHANNEL_NAME
     *
     * @mbggenerated
     */
    private String smsChannelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.PRODUCT
     *
     * @mbggenerated
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.DOMAIN
     *
     * @mbggenerated
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.ACCESS_KEY_ID
     *
     * @mbggenerated
     */
    private String accessKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.ACCESS_KEY_SECRET
     *
     * @mbggenerated
     */
    private String accessKeySecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.CONNECT_TIMEOUT
     *
     * @mbggenerated
     */
    private Integer connectTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.READ_TIMEOUT
     *
     * @mbggenerated
     */
    private Integer readTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.SIGN_NAME
     *
     * @mbggenerated
     */
    private String signName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.TEMPLICATE_CODE
     *
     * @mbggenerated
     */
    private String templicateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.TEMPLICATE_PARAM
     *
     * @mbggenerated
     */
    private String templicateParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ALISMS_CONFIG.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.SMS_CHANNEL_ID
     *
     * @return the value of TBL_ALISMS_CONFIG.SMS_CHANNEL_ID
     *
     * @mbggenerated
     */
    public String getSmsChannelId() {
        return smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.SMS_CHANNEL_ID
     *
     * @param smsChannelId the value for TBL_ALISMS_CONFIG.SMS_CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setSmsChannelId(String smsChannelId) {
        this.smsChannelId = smsChannelId == null ? null : smsChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.SMS_CHANNEL_NAME
     *
     * @return the value of TBL_ALISMS_CONFIG.SMS_CHANNEL_NAME
     *
     * @mbggenerated
     */
    public String getSmsChannelName() {
        return smsChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.SMS_CHANNEL_NAME
     *
     * @param smsChannelName the value for TBL_ALISMS_CONFIG.SMS_CHANNEL_NAME
     *
     * @mbggenerated
     */
    public void setSmsChannelName(String smsChannelName) {
        this.smsChannelName = smsChannelName == null ? null : smsChannelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.PRODUCT
     *
     * @return the value of TBL_ALISMS_CONFIG.PRODUCT
     *
     * @mbggenerated
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.PRODUCT
     *
     * @param product the value for TBL_ALISMS_CONFIG.PRODUCT
     *
     * @mbggenerated
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.DOMAIN
     *
     * @return the value of TBL_ALISMS_CONFIG.DOMAIN
     *
     * @mbggenerated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.DOMAIN
     *
     * @param domain the value for TBL_ALISMS_CONFIG.DOMAIN
     *
     * @mbggenerated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.ACCESS_KEY_ID
     *
     * @return the value of TBL_ALISMS_CONFIG.ACCESS_KEY_ID
     *
     * @mbggenerated
     */
    public String getAccessKeyId() {
        return accessKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.ACCESS_KEY_ID
     *
     * @param accessKeyId the value for TBL_ALISMS_CONFIG.ACCESS_KEY_ID
     *
     * @mbggenerated
     */
    public void setAccessKeyId(String accessKeyId) {
        this.accessKeyId = accessKeyId == null ? null : accessKeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.ACCESS_KEY_SECRET
     *
     * @return the value of TBL_ALISMS_CONFIG.ACCESS_KEY_SECRET
     *
     * @mbggenerated
     */
    public String getAccessKeySecret() {
        return accessKeySecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.ACCESS_KEY_SECRET
     *
     * @param accessKeySecret the value for TBL_ALISMS_CONFIG.ACCESS_KEY_SECRET
     *
     * @mbggenerated
     */
    public void setAccessKeySecret(String accessKeySecret) {
        this.accessKeySecret = accessKeySecret == null ? null : accessKeySecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.CONNECT_TIMEOUT
     *
     * @return the value of TBL_ALISMS_CONFIG.CONNECT_TIMEOUT
     *
     * @mbggenerated
     */
    public Integer getConnectTimeout() {
        return connectTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.CONNECT_TIMEOUT
     *
     * @param connectTimeout the value for TBL_ALISMS_CONFIG.CONNECT_TIMEOUT
     *
     * @mbggenerated
     */
    public void setConnectTimeout(Integer connectTimeout) {
        this.connectTimeout = connectTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.READ_TIMEOUT
     *
     * @return the value of TBL_ALISMS_CONFIG.READ_TIMEOUT
     *
     * @mbggenerated
     */
    public Integer getReadTimeout() {
        return readTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.READ_TIMEOUT
     *
     * @param readTimeout the value for TBL_ALISMS_CONFIG.READ_TIMEOUT
     *
     * @mbggenerated
     */
    public void setReadTimeout(Integer readTimeout) {
        this.readTimeout = readTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.SIGN_NAME
     *
     * @return the value of TBL_ALISMS_CONFIG.SIGN_NAME
     *
     * @mbggenerated
     */
    public String getSignName() {
        return signName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.SIGN_NAME
     *
     * @param signName the value for TBL_ALISMS_CONFIG.SIGN_NAME
     *
     * @mbggenerated
     */
    public void setSignName(String signName) {
        this.signName = signName == null ? null : signName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.TEMPLICATE_CODE
     *
     * @return the value of TBL_ALISMS_CONFIG.TEMPLICATE_CODE
     *
     * @mbggenerated
     */
    public String getTemplicateCode() {
        return templicateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.TEMPLICATE_CODE
     *
     * @param templicateCode the value for TBL_ALISMS_CONFIG.TEMPLICATE_CODE
     *
     * @mbggenerated
     */
    public void setTemplicateCode(String templicateCode) {
        this.templicateCode = templicateCode == null ? null : templicateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.TEMPLICATE_PARAM
     *
     * @return the value of TBL_ALISMS_CONFIG.TEMPLICATE_PARAM
     *
     * @mbggenerated
     */
    public String getTemplicateParam() {
        return templicateParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.TEMPLICATE_PARAM
     *
     * @param templicateParam the value for TBL_ALISMS_CONFIG.TEMPLICATE_PARAM
     *
     * @mbggenerated
     */
    public void setTemplicateParam(String templicateParam) {
        this.templicateParam = templicateParam == null ? null : templicateParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ALISMS_CONFIG.STATUS
     *
     * @return the value of TBL_ALISMS_CONFIG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ALISMS_CONFIG.STATUS
     *
     * @param status the value for TBL_ALISMS_CONFIG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}