package com.company.core.dao;

public class TblSmsRecordDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SMS_ORDER_NO
     *
     * @mbggenerated
     */
    private String smsOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SMS_TYPE
     *
     * @mbggenerated
     */
    private String smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SMS_CHANNEL_CAT
     *
     * @mbggenerated
     */
    private String smsChannelCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SMS_CHANNEL_ID
     *
     * @mbggenerated
     */
    private String smsChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SEND_DATE
     *
     * @mbggenerated
     */
    private String sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SEND_TIME
     *
     * @mbggenerated
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.VERIFY_DATE
     *
     * @mbggenerated
     */
    private String verifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.VERIFY_TIME
     *
     * @mbggenerated
     */
    private String verifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.SEND_CONTENT
     *
     * @mbggenerated
     */
    private String sendContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.RESPONSE_REQUEST_ID
     *
     * @mbggenerated
     */
    private String responseRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.RETURN_CODE
     *
     * @mbggenerated
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.RETURN_MSG
     *
     * @mbggenerated
     */
    private String returnMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SMS_ORDER_NO
     *
     * @return the value of TBL_SMS_RECORD.SMS_ORDER_NO
     *
     * @mbggenerated
     */
    public String getSmsOrderNo() {
        return smsOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SMS_ORDER_NO
     *
     * @param smsOrderNo the value for TBL_SMS_RECORD.SMS_ORDER_NO
     *
     * @mbggenerated
     */
    public void setSmsOrderNo(String smsOrderNo) {
        this.smsOrderNo = smsOrderNo == null ? null : smsOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.PHONE_NUMBER
     *
     * @return the value of TBL_SMS_RECORD.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.PHONE_NUMBER
     *
     * @param phoneNumber the value for TBL_SMS_RECORD.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SMS_TYPE
     *
     * @return the value of TBL_SMS_RECORD.SMS_TYPE
     *
     * @mbggenerated
     */
    public String getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SMS_TYPE
     *
     * @param smsType the value for TBL_SMS_RECORD.SMS_TYPE
     *
     * @mbggenerated
     */
    public void setSmsType(String smsType) {
        this.smsType = smsType == null ? null : smsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SMS_CHANNEL_CAT
     *
     * @return the value of TBL_SMS_RECORD.SMS_CHANNEL_CAT
     *
     * @mbggenerated
     */
    public String getSmsChannelCat() {
        return smsChannelCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SMS_CHANNEL_CAT
     *
     * @param smsChannelCat the value for TBL_SMS_RECORD.SMS_CHANNEL_CAT
     *
     * @mbggenerated
     */
    public void setSmsChannelCat(String smsChannelCat) {
        this.smsChannelCat = smsChannelCat == null ? null : smsChannelCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SMS_CHANNEL_ID
     *
     * @return the value of TBL_SMS_RECORD.SMS_CHANNEL_ID
     *
     * @mbggenerated
     */
    public String getSmsChannelId() {
        return smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SMS_CHANNEL_ID
     *
     * @param smsChannelId the value for TBL_SMS_RECORD.SMS_CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setSmsChannelId(String smsChannelId) {
        this.smsChannelId = smsChannelId == null ? null : smsChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SEND_DATE
     *
     * @return the value of TBL_SMS_RECORD.SEND_DATE
     *
     * @mbggenerated
     */
    public String getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SEND_DATE
     *
     * @param sendDate the value for TBL_SMS_RECORD.SEND_DATE
     *
     * @mbggenerated
     */
    public void setSendDate(String sendDate) {
        this.sendDate = sendDate == null ? null : sendDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SEND_TIME
     *
     * @return the value of TBL_SMS_RECORD.SEND_TIME
     *
     * @mbggenerated
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SEND_TIME
     *
     * @param sendTime the value for TBL_SMS_RECORD.SEND_TIME
     *
     * @mbggenerated
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime == null ? null : sendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.VERIFY_DATE
     *
     * @return the value of TBL_SMS_RECORD.VERIFY_DATE
     *
     * @mbggenerated
     */
    public String getVerifyDate() {
        return verifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.VERIFY_DATE
     *
     * @param verifyDate the value for TBL_SMS_RECORD.VERIFY_DATE
     *
     * @mbggenerated
     */
    public void setVerifyDate(String verifyDate) {
        this.verifyDate = verifyDate == null ? null : verifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.VERIFY_TIME
     *
     * @return the value of TBL_SMS_RECORD.VERIFY_TIME
     *
     * @mbggenerated
     */
    public String getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.VERIFY_TIME
     *
     * @param verifyTime the value for TBL_SMS_RECORD.VERIFY_TIME
     *
     * @mbggenerated
     */
    public void setVerifyTime(String verifyTime) {
        this.verifyTime = verifyTime == null ? null : verifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.STATUS
     *
     * @return the value of TBL_SMS_RECORD.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.STATUS
     *
     * @param status the value for TBL_SMS_RECORD.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.SEND_CONTENT
     *
     * @return the value of TBL_SMS_RECORD.SEND_CONTENT
     *
     * @mbggenerated
     */
    public String getSendContent() {
        return sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.SEND_CONTENT
     *
     * @param sendContent the value for TBL_SMS_RECORD.SEND_CONTENT
     *
     * @mbggenerated
     */
    public void setSendContent(String sendContent) {
        this.sendContent = sendContent == null ? null : sendContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.RESPONSE_REQUEST_ID
     *
     * @return the value of TBL_SMS_RECORD.RESPONSE_REQUEST_ID
     *
     * @mbggenerated
     */
    public String getResponseRequestId() {
        return responseRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.RESPONSE_REQUEST_ID
     *
     * @param responseRequestId the value for TBL_SMS_RECORD.RESPONSE_REQUEST_ID
     *
     * @mbggenerated
     */
    public void setResponseRequestId(String responseRequestId) {
        this.responseRequestId = responseRequestId == null ? null : responseRequestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.RETURN_CODE
     *
     * @return the value of TBL_SMS_RECORD.RETURN_CODE
     *
     * @mbggenerated
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.RETURN_CODE
     *
     * @param returnCode the value for TBL_SMS_RECORD.RETURN_CODE
     *
     * @mbggenerated
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.RETURN_MSG
     *
     * @return the value of TBL_SMS_RECORD.RETURN_MSG
     *
     * @mbggenerated
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.RETURN_MSG
     *
     * @param returnMsg the value for TBL_SMS_RECORD.RETURN_MSG
     *
     * @mbggenerated
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }
}