package com.company.core.dao;

import java.util.ArrayList;
import java.util.List;

public class TblSmsRecordDAOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public TblSmsRecordDAOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSmsOrderNoIsNull() {
            addCriterion("SMS_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoIsNotNull() {
            addCriterion("SMS_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoEqualTo(String value) {
            addCriterion("SMS_ORDER_NO =", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoNotEqualTo(String value) {
            addCriterion("SMS_ORDER_NO <>", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoGreaterThan(String value) {
            addCriterion("SMS_ORDER_NO >", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_ORDER_NO >=", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoLessThan(String value) {
            addCriterion("SMS_ORDER_NO <", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoLessThanOrEqualTo(String value) {
            addCriterion("SMS_ORDER_NO <=", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoLike(String value) {
            addCriterion("SMS_ORDER_NO like", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoNotLike(String value) {
            addCriterion("SMS_ORDER_NO not like", value, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoIn(List<String> values) {
            addCriterion("SMS_ORDER_NO in", values, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoNotIn(List<String> values) {
            addCriterion("SMS_ORDER_NO not in", values, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoBetween(String value1, String value2) {
            addCriterion("SMS_ORDER_NO between", value1, value2, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andSmsOrderNoNotBetween(String value1, String value2) {
            addCriterion("SMS_ORDER_NO not between", value1, value2, "smsOrderNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("PHONE_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("PHONE_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("PHONE_NUMBER =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("PHONE_NUMBER <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("PHONE_NUMBER >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("PHONE_NUMBER <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("PHONE_NUMBER like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("PHONE_NUMBER not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("PHONE_NUMBER in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("PHONE_NUMBER not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("PHONE_NUMBER between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("PHONE_NUMBER not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andSmsTypeIsNull() {
            addCriterion("SMS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSmsTypeIsNotNull() {
            addCriterion("SMS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSmsTypeEqualTo(String value) {
            addCriterion("SMS_TYPE =", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotEqualTo(String value) {
            addCriterion("SMS_TYPE <>", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeGreaterThan(String value) {
            addCriterion("SMS_TYPE >", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_TYPE >=", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeLessThan(String value) {
            addCriterion("SMS_TYPE <", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeLessThanOrEqualTo(String value) {
            addCriterion("SMS_TYPE <=", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeLike(String value) {
            addCriterion("SMS_TYPE like", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotLike(String value) {
            addCriterion("SMS_TYPE not like", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeIn(List<String> values) {
            addCriterion("SMS_TYPE in", values, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotIn(List<String> values) {
            addCriterion("SMS_TYPE not in", values, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeBetween(String value1, String value2) {
            addCriterion("SMS_TYPE between", value1, value2, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotBetween(String value1, String value2) {
            addCriterion("SMS_TYPE not between", value1, value2, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatIsNull() {
            addCriterion("SMS_CHANNEL_CAT is null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatIsNotNull() {
            addCriterion("SMS_CHANNEL_CAT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CAT =", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatNotEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CAT <>", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatGreaterThan(String value) {
            addCriterion("SMS_CHANNEL_CAT >", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CAT >=", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatLessThan(String value) {
            addCriterion("SMS_CHANNEL_CAT <", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatLessThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CAT <=", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatLike(String value) {
            addCriterion("SMS_CHANNEL_CAT like", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatNotLike(String value) {
            addCriterion("SMS_CHANNEL_CAT not like", value, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatIn(List<String> values) {
            addCriterion("SMS_CHANNEL_CAT in", values, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatNotIn(List<String> values) {
            addCriterion("SMS_CHANNEL_CAT not in", values, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_CAT between", value1, value2, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCatNotBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_CAT not between", value1, value2, "smsChannelCat");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdIsNull() {
            addCriterion("SMS_CHANNEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdIsNotNull() {
            addCriterion("SMS_CHANNEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdEqualTo(String value) {
            addCriterion("SMS_CHANNEL_ID =", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdNotEqualTo(String value) {
            addCriterion("SMS_CHANNEL_ID <>", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdGreaterThan(String value) {
            addCriterion("SMS_CHANNEL_ID >", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_ID >=", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdLessThan(String value) {
            addCriterion("SMS_CHANNEL_ID <", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdLessThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_ID <=", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdLike(String value) {
            addCriterion("SMS_CHANNEL_ID like", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdNotLike(String value) {
            addCriterion("SMS_CHANNEL_ID not like", value, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdIn(List<String> values) {
            addCriterion("SMS_CHANNEL_ID in", values, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdNotIn(List<String> values) {
            addCriterion("SMS_CHANNEL_ID not in", values, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_ID between", value1, value2, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelIdNotBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_ID not between", value1, value2, "smsChannelId");
            return (Criteria) this;
        }

        public Criteria andSendDateIsNull() {
            addCriterion("SEND_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSendDateIsNotNull() {
            addCriterion("SEND_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSendDateEqualTo(String value) {
            addCriterion("SEND_DATE =", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateNotEqualTo(String value) {
            addCriterion("SEND_DATE <>", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateGreaterThan(String value) {
            addCriterion("SEND_DATE >", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_DATE >=", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateLessThan(String value) {
            addCriterion("SEND_DATE <", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateLessThanOrEqualTo(String value) {
            addCriterion("SEND_DATE <=", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateLike(String value) {
            addCriterion("SEND_DATE like", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateNotLike(String value) {
            addCriterion("SEND_DATE not like", value, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateIn(List<String> values) {
            addCriterion("SEND_DATE in", values, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateNotIn(List<String> values) {
            addCriterion("SEND_DATE not in", values, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateBetween(String value1, String value2) {
            addCriterion("SEND_DATE between", value1, value2, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateNotBetween(String value1, String value2) {
            addCriterion("SEND_DATE not between", value1, value2, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("SEND_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("SEND_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(String value) {
            addCriterion("SEND_TIME =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(String value) {
            addCriterion("SEND_TIME <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(String value) {
            addCriterion("SEND_TIME >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_TIME >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(String value) {
            addCriterion("SEND_TIME <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(String value) {
            addCriterion("SEND_TIME <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLike(String value) {
            addCriterion("SEND_TIME like", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotLike(String value) {
            addCriterion("SEND_TIME not like", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<String> values) {
            addCriterion("SEND_TIME in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<String> values) {
            addCriterion("SEND_TIME not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(String value1, String value2) {
            addCriterion("SEND_TIME between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(String value1, String value2) {
            addCriterion("SEND_TIME not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andVerifyDateIsNull() {
            addCriterion("VERIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andVerifyDateIsNotNull() {
            addCriterion("VERIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyDateEqualTo(String value) {
            addCriterion("VERIFY_DATE =", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateNotEqualTo(String value) {
            addCriterion("VERIFY_DATE <>", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateGreaterThan(String value) {
            addCriterion("VERIFY_DATE >", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_DATE >=", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateLessThan(String value) {
            addCriterion("VERIFY_DATE <", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_DATE <=", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateLike(String value) {
            addCriterion("VERIFY_DATE like", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateNotLike(String value) {
            addCriterion("VERIFY_DATE not like", value, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateIn(List<String> values) {
            addCriterion("VERIFY_DATE in", values, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateNotIn(List<String> values) {
            addCriterion("VERIFY_DATE not in", values, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateBetween(String value1, String value2) {
            addCriterion("VERIFY_DATE between", value1, value2, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyDateNotBetween(String value1, String value2) {
            addCriterion("VERIFY_DATE not between", value1, value2, "verifyDate");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeIsNull() {
            addCriterion("VERIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeIsNotNull() {
            addCriterion("VERIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeEqualTo(String value) {
            addCriterion("VERIFY_TIME =", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotEqualTo(String value) {
            addCriterion("VERIFY_TIME <>", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeGreaterThan(String value) {
            addCriterion("VERIFY_TIME >", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME >=", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeLessThan(String value) {
            addCriterion("VERIFY_TIME <", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_TIME <=", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeLike(String value) {
            addCriterion("VERIFY_TIME like", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotLike(String value) {
            addCriterion("VERIFY_TIME not like", value, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeIn(List<String> values) {
            addCriterion("VERIFY_TIME in", values, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotIn(List<String> values) {
            addCriterion("VERIFY_TIME not in", values, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME between", value1, value2, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andVerifyTimeNotBetween(String value1, String value2) {
            addCriterion("VERIFY_TIME not between", value1, value2, "verifyTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSendContentIsNull() {
            addCriterion("SEND_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andSendContentIsNotNull() {
            addCriterion("SEND_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andSendContentEqualTo(String value) {
            addCriterion("SEND_CONTENT =", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotEqualTo(String value) {
            addCriterion("SEND_CONTENT <>", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentGreaterThan(String value) {
            addCriterion("SEND_CONTENT >", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_CONTENT >=", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentLessThan(String value) {
            addCriterion("SEND_CONTENT <", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentLessThanOrEqualTo(String value) {
            addCriterion("SEND_CONTENT <=", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentLike(String value) {
            addCriterion("SEND_CONTENT like", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotLike(String value) {
            addCriterion("SEND_CONTENT not like", value, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentIn(List<String> values) {
            addCriterion("SEND_CONTENT in", values, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotIn(List<String> values) {
            addCriterion("SEND_CONTENT not in", values, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentBetween(String value1, String value2) {
            addCriterion("SEND_CONTENT between", value1, value2, "sendContent");
            return (Criteria) this;
        }

        public Criteria andSendContentNotBetween(String value1, String value2) {
            addCriterion("SEND_CONTENT not between", value1, value2, "sendContent");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdIsNull() {
            addCriterion("RESPONSE_REQUEST_ID is null");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdIsNotNull() {
            addCriterion("RESPONSE_REQUEST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdEqualTo(String value) {
            addCriterion("RESPONSE_REQUEST_ID =", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdNotEqualTo(String value) {
            addCriterion("RESPONSE_REQUEST_ID <>", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdGreaterThan(String value) {
            addCriterion("RESPONSE_REQUEST_ID >", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdGreaterThanOrEqualTo(String value) {
            addCriterion("RESPONSE_REQUEST_ID >=", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdLessThan(String value) {
            addCriterion("RESPONSE_REQUEST_ID <", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdLessThanOrEqualTo(String value) {
            addCriterion("RESPONSE_REQUEST_ID <=", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdLike(String value) {
            addCriterion("RESPONSE_REQUEST_ID like", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdNotLike(String value) {
            addCriterion("RESPONSE_REQUEST_ID not like", value, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdIn(List<String> values) {
            addCriterion("RESPONSE_REQUEST_ID in", values, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdNotIn(List<String> values) {
            addCriterion("RESPONSE_REQUEST_ID not in", values, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdBetween(String value1, String value2) {
            addCriterion("RESPONSE_REQUEST_ID between", value1, value2, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andResponseRequestIdNotBetween(String value1, String value2) {
            addCriterion("RESPONSE_REQUEST_ID not between", value1, value2, "responseRequestId");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIsNull() {
            addCriterion("RETURN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIsNotNull() {
            addCriterion("RETURN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeEqualTo(String value) {
            addCriterion("RETURN_CODE =", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotEqualTo(String value) {
            addCriterion("RETURN_CODE <>", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeGreaterThan(String value) {
            addCriterion("RETURN_CODE >", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RETURN_CODE >=", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLessThan(String value) {
            addCriterion("RETURN_CODE <", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLessThanOrEqualTo(String value) {
            addCriterion("RETURN_CODE <=", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLike(String value) {
            addCriterion("RETURN_CODE like", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotLike(String value) {
            addCriterion("RETURN_CODE not like", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIn(List<String> values) {
            addCriterion("RETURN_CODE in", values, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotIn(List<String> values) {
            addCriterion("RETURN_CODE not in", values, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeBetween(String value1, String value2) {
            addCriterion("RETURN_CODE between", value1, value2, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotBetween(String value1, String value2) {
            addCriterion("RETURN_CODE not between", value1, value2, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnMsgIsNull() {
            addCriterion("RETURN_MSG is null");
            return (Criteria) this;
        }

        public Criteria andReturnMsgIsNotNull() {
            addCriterion("RETURN_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andReturnMsgEqualTo(String value) {
            addCriterion("RETURN_MSG =", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotEqualTo(String value) {
            addCriterion("RETURN_MSG <>", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgGreaterThan(String value) {
            addCriterion("RETURN_MSG >", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgGreaterThanOrEqualTo(String value) {
            addCriterion("RETURN_MSG >=", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgLessThan(String value) {
            addCriterion("RETURN_MSG <", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgLessThanOrEqualTo(String value) {
            addCriterion("RETURN_MSG <=", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgLike(String value) {
            addCriterion("RETURN_MSG like", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotLike(String value) {
            addCriterion("RETURN_MSG not like", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgIn(List<String> values) {
            addCriterion("RETURN_MSG in", values, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotIn(List<String> values) {
            addCriterion("RETURN_MSG not in", values, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgBetween(String value1, String value2) {
            addCriterion("RETURN_MSG between", value1, value2, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotBetween(String value1, String value2) {
            addCriterion("RETURN_MSG not between", value1, value2, "returnMsg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_SMS_RECORD
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}