package com.company.core.dao;

public class TblSmsVerifyCodeDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_VERIFY_CODE.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_VERIFY_CODE.VERIFY_CODE
     *
     * @mbggenerated
     */
    private String verifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_VERIFY_CODE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_VERIFY_CODE.SEND_DATE_TIME
     *
     * @mbggenerated
     */
    private String sendDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_VERIFY_CODE.EXPIRE_DATE_TIME
     *
     * @mbggenerated
     */
    private String expireDateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_VERIFY_CODE.PHONE_NUMBER
     *
     * @return the value of TBL_SMS_VERIFY_CODE.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_VERIFY_CODE.PHONE_NUMBER
     *
     * @param phoneNumber the value for TBL_SMS_VERIFY_CODE.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_VERIFY_CODE.VERIFY_CODE
     *
     * @return the value of TBL_SMS_VERIFY_CODE.VERIFY_CODE
     *
     * @mbggenerated
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_VERIFY_CODE.VERIFY_CODE
     *
     * @param verifyCode the value for TBL_SMS_VERIFY_CODE.VERIFY_CODE
     *
     * @mbggenerated
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode == null ? null : verifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_VERIFY_CODE.STATUS
     *
     * @return the value of TBL_SMS_VERIFY_CODE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_VERIFY_CODE.STATUS
     *
     * @param status the value for TBL_SMS_VERIFY_CODE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_VERIFY_CODE.SEND_DATE_TIME
     *
     * @return the value of TBL_SMS_VERIFY_CODE.SEND_DATE_TIME
     *
     * @mbggenerated
     */
    public String getSendDateTime() {
        return sendDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_VERIFY_CODE.SEND_DATE_TIME
     *
     * @param sendDateTime the value for TBL_SMS_VERIFY_CODE.SEND_DATE_TIME
     *
     * @mbggenerated
     */
    public void setSendDateTime(String sendDateTime) {
        this.sendDateTime = sendDateTime == null ? null : sendDateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_VERIFY_CODE.EXPIRE_DATE_TIME
     *
     * @return the value of TBL_SMS_VERIFY_CODE.EXPIRE_DATE_TIME
     *
     * @mbggenerated
     */
    public String getExpireDateTime() {
        return expireDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_VERIFY_CODE.EXPIRE_DATE_TIME
     *
     * @param expireDateTime the value for TBL_SMS_VERIFY_CODE.EXPIRE_DATE_TIME
     *
     * @mbggenerated
     */
    public void setExpireDateTime(String expireDateTime) {
        this.expireDateTime = expireDateTime == null ? null : expireDateTime.trim();
    }
}